name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - app.py
      - Dockerfile
      - .github/**
      - templates/**
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3     
   
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ahmedmohamedawad
          password: ${{ secrets.DOCKER_PASSWORD }}

      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ahmedmohamedawad/personalblog:latest,ahmedmohamedawad/personalblog:${{ github.ref_name }}
         
